namespace Pyle.Core.Enums
{
    public enum Endpoint
    {
        Answers,
        AssociatedAccounts,
        CreateQuestion,
        DownvoteAnswer,
        DownvoteQuestion,
        FavoriteQuestion,
        Inbox,
        Me,
        MyAssociatedAccounts,
        MyFullReputationHistory,
        MyTimeline,
        QuestionAnswers,
        Questions,
        QuestionsById,
        Sites,
        Tags,
        UndoDownvoteAnswer,
        UndoDownvoteQuestion,
        UndoUpvoteAnswer,
        UndoUpvoteQuestion,
        UnfavoriteQuestion,
        UpvoteAnswer,
        UpvoteQuestion
    }
}
